server:
  port: 7010
spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServerDialect
    database: sql_server
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: cards_user
    password: pass
    url: jdbc:sqlserver://localhost:1433;databaseName=Cards
accounts:
  allow-get-accounts: true